[general]
live_config_reload = true

[terminal.shell]
args = ['--login']
program = "zsh"

[cursor]
style = "Beam"

[font]
size = 12.0

[font.normal]
family = "RobotoMono Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1

[window.padding]
x = 0
y = 0

[colors.primary]
background = "#030303"

[colors.normal]
black = "#d0d0d0"
red = "#ff3b3b"
green = "#c082ff"
yellow = "#ffd54a"
blue = "#35baf6"
magenta = "#ff3ef3"
cyan = "#18c2e6"
white = "#e3e8ff"

[colors.bright]
black = "#e0e0e0"
red = "#ff5555"
green = "#d29cff"
yellow = "#ffdd66"
blue = "#4cbaff"
magenta = "#ff5aff"
cyan = "#22e0df"
white = "#eef1ff"

[colors.dim]
black = "#b6b6b6"
red = "#b03232"
green = "#a96cee"
yellow = "#d9b640"
blue = "#2a8ed1"
magenta = "#d63acc"
cyan = "#0f6f75"
white = "#cdd3e9"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[terminal]
